spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true